paths:
  /tenants/{tenantId}/settings:
    get:
      tags: [Settings]
      summary: Get tenant settings
      parameters:
        - $ref: ../components/parameters/common.yaml#/TenantId
      responses:
        '200': { description: OK }
    patch:
      tags: [Settings]
      summary: Update tenant settings
      parameters:
        - $ref: ../components/parameters/common.yaml#/TenantId
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '200': { description: Updated }